name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
        #Step 1: Checkout the repository 
      - name: Checkout
        uses: actions/checkout@v4
        #Step 2: Install node.js 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the Node.js version
        # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install
        # Step 4: Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          browser: chrome